stages:

  clean:
    cmd: python -m src.data.data_cleaner
    deps:
      - data/raw/credit_risk.csv
      - src/data/data_cleaner.py
    outs:
      - data/processed/credit_risk_cleaned.csv

  preprocess:
    cmd: python -m src.preprocessing.data_pipeline
    deps:
      - data/processed/credit_risk_cleaned.csv
      - src/features/feature_engineer.py
      - src/preprocessing/preprocessor.py
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      - data/processed/preprocessor.joblib
      - data/processed/feature_engineer.joblib
  train_models:
    cmd: python -m src.models.model_training_pipeline
    deps:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      - src/preprocessing/imbalance_handler.py
      - src/models/hyperparameter_tuner.py
      - src/models/model_trainer.py
      - src/models/model_evaluator.py
      - src/models/mlflow_tracker.py
      - src/database/prediction_logger.py
      - src/config/data_config.yaml
      - src/config/params.yaml
    outs:
      - data/processed/X_train_balanced.csv
      - data/processed/y_train_balanced.csv
      - data/artifacts/best_hyperparams.json
      - data/artifacts/random_forest.joblib
      - data/artifacts/xgboost.joblib
      - data/artifacts/neural_network.joblib
      - data/artifacts/model_results.joblib
      - data/processed/credit_risk_featured.csv
      - data/processed/data_info.joblib